# Generated by Django 4.0.4 on 2023-03-05 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lead_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.leadsource'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='crm.project'),
        ),
        migrations.AlterField(
            model_name='session',
            name='sess_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sessionsservicesmap',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='crm.session'),
        ),
    ]
