# Generated by Django 4.0.4 on 2023-03-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='es_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
