# Generated by Django 4.0.4 on 2023-03-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_estimate_es_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='cost',
            new_name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='service',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estimate',
            name='es_dliverables',
            field=models.ManyToManyField(related_name='estimate_for_dliverables', to='crm.deliverable'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='es_sessions',
            field=models.ManyToManyField(related_name='estimate_for_sessions', to='crm.session'),
        ),
    ]
